spring:
  cache:
    jcache:
      config: 'classpath:ehcache.xml'
# TODO: trying yml format. Perhaps above wont work
resilience4j.retry:
  configs:
    default:
      maxAttempts: 5
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html